---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
  String::Slice: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-ZeroCopy
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  bugtracker: https://github.com/hoytech/Test-ZeroCopy/issues
  repository: git://github.com/hoytech/Test-ZeroCopy.git
version: 0.100
